import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const projectRoot = join(__dirname, "..");
const pdfDir = join(projectRoot, "src", "private", "res");

// Read PDFs and convert to Base64
const esBuffer = readFileSync(join(pdfDir, "German_Gomez_es.pdf"));
const enBuffer = readFileSync(join(pdfDir, "German_Gomez_en.pdf"));

const esBase64 = esBuffer.toString("base64");
const enBase64 = enBuffer.toString("base64");

// Generate TypeScript module
const content = `// Auto-generated by scripts/encode-pdfs.js
// DO NOT EDIT MANUALLY

export const CV_BASE64 = {
  es: '${esBase64}',
  en: '${enBase64}',
} as const;

export function getCVBuffer(language: 'es' | 'en'): Uint8Array {
  const base64 = CV_BASE64[language];
  // Decode base64 to binary string
  const binaryString = atob(base64);
  // Convert to Uint8Array (works in Cloudflare Workers)
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}
`;

writeFileSync(join(projectRoot, "src", "lib", "cv-data.ts"), content, "utf-8");

console.log("✅ PDFs encoded successfully!");
console.log(`   ES PDF: ${(esBase64.length / 1024).toFixed(2)} KB (base64)`);
console.log(`   EN PDF: ${(enBase64.length / 1024).toFixed(2)} KB (base64)`);
